<?php
 
/**
 * Reference: http://xebee.xebia.in/2011/06/14/drupal-webform-add-a-dynamic-select-option-list/
 * The following piece of code is based on the blog post above written by Anubhav
 */
 
function webform_options_webform_select_options_info() {
  $items = array();
  if (function_exists('_get_node_titles')) {
    $items['node_titles'] = array(
      'title' => t('Node titles'),
      'options callback' => '_get_node_titles',
    );
  }
  return $items;
}
 
function _get_node_titles() {
  $options = array();
 $result = db_query("SELECT tid, name FROM {taxonomy_term_data} ");
  
  foreach ($result as $row) {
    $options[$row->tid] = $row->name;
  }
  return $options;
}